language: node_js
node_js:
- '0.12'
env:
  global:
    secure: lJr0/B0pbEUElmHv0C53YhnqunoEXk9meJMqRSM0k0BlSXyddwvxuHdUzZ8tngBjqNLi6VkPeOTHGDrr7/beuB1YL/v+DJElwlrkHQnhi62gTVfyC8pjRGeToeP0tGNp3gofsCxJ9ZK7JMZz4laVirQkwhoRA6YAAS/RfDo/Aw4IrHI5oV2qfjYZcNGwAI2lPLKQDSwZQmbb9e8hqu+7DjABRTp06KCErs0r74nSGUdVMKkSRPt++DG2+UsTJkzPkj2sQWd50QjR8vHoKBDCS2Sj7l/tC8B/UNcn/CzKby3ayhmpgFW1GdDXqo5u+1e4OyzZedqCLIAvZqsJZfPMKw01jg6M4DR77ZKbNAq1eWvGbfLF0gwdwAOofkpr6avtwV4x4nBnHkAV6W/mZUlpHXhHtw+3JpofQUFu+39e1s9f9f2LXGUc6UnhrqbOU9ykY1kusO2mILsGvzpbnxtKMcsLacvUPQaV/uptls2XhOjMrvpI1DIAWQACuvioZC9O7JnzIvw9ZfomsL2NHknbi6BHXRzMt9TlKvITiKZAXfjeqH4aIYzj6XvPUk+ILhNtSZpx2FAIA8Lle+qS3oxBbPBxdHkeAzX6+at/v/gJJ1Nd7cew2odSMYwBn33FuqS6DMXjzpdbklgGdV9LmkCnS4mAJVNA1Tszs3xWw5JYA00=
